{% set version = "0.8.1" %}

package:
  name: taplo
  version: {{ version }}

source:
  url: https://github.com/tamasfe/taplo/archive/refs/tags/{{ version }}.tar.gz
  sha256: ec8dfdcfa33a6855803286413c0603140b21c06bc659ceab7e2ddc05baf1a8b3

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - cargo-bundle-licenses
  host:
    - clangdev  # [not osx]
    - llvmdev  # [not osx]

test:
  requires:
    - m2-grep  # [win]
  commands:
    - taplo --version
    - taplo --help
    - taplo --version | grep -iE "taplo {{ version.replace(".", "\.") }}"

about:
  home: https://github.com/tamasfe/taplo
  license: MIT
  license_family: MIT
  summary: A TOML toolkit written in Rust
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
