{% set version = "0.13.0" %}

package:
  name: taplo
  version: {{ version }}

source:
  url: https://github.com/tamasfe/taplo/archive/refs/tags/release-taplo-{{ version }}.tar.gz
  sha256: b63ea85fea3f3c7982b9a75a26627c62773623dd6ba681d717891fd9257a6629

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - cargo-bundle-licenses
  host:
    - clangdev  # [not osx]
    - llvmdev   # [not osx]
    - openssl   # [unix]

test:
  requires:
    - m2-grep  # [win]
  commands:
    - taplo --version
    - taplo --help
    - taplo --version | grep -iE "taplo {{ version.replace(".", "\.") }}"

about:
  home: https://github.com/tamasfe/taplo
  license: MIT
  license_family: MIT
  summary: A TOML toolkit written in Rust
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
